### ISSUE TITLE
Can't delete notiofication in realm currency.

### ISSUE THREAD

**Issue by dspjm** [URK96/ResinTimer#20] opened 2021-09-23 12:08 UTC
Having three timers. After selecting an item and click the minus button, nothing happens.

**Comment by URK96** [comment] 2021-09-23 12:15
Thanks to report bugs. I finish to check that issue and i fix it now. Update will upload soon.

**Comment by selurvedu** [comment] 2021-09-23 18:42
Duplicate of #18.

**Comment by URK96** [comment] 2021-09-24 01:47
Update version upload complete. You can download today or tomorrow.

**Closed by URK96** 2021-09-24 01:47 UTC
